//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Degrey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int ProID { get; set; }
        public string ProImage { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProDetail ProDetail { get; set; }
    }
}
